config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get 'about', to: 'pages#about'
  get 'tos', to: 'pages#tos'
  get 'practice', to: 'pages#practice'
  get 'login', to: 'pages#login'
  get 'course_details', to: 'pages#course_details'
  get 'free', to: 'pages#curriculum', as: :course_signup
  get '/sitemap.xml', to: redirect("https://jigsaw-labs-student.s3.amazonaws.com/sitemap.xml")
  post 'update_application', to: 'applications#update_app', as: 'update_app'
  resources :events
  get '/events_path' => redirect("https://www.meetup.com/Data-Workshops/events/"), :as => :events_path
  get '/applications/new' => redirect("https://calendly.com/jigsaw-labs/information-chat"), :as => :new_application_path
  resources :applications

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_apply_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    
    
    <style>
@font-face {
  src: url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.eot");
  src: url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.eot?#iefix") format("embedded-opentype"), url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.woff2") format("woff2"), url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.woff") format("woff"), url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.svg#Typotheque_webfonts_service") format("svg");
}

 <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Actor" />
    </style>
  </head>
  <body class=" ">
    <div class="Nav__wrapper   Nav__wrapper--opaque ">
      <nav class="Nav">
        <a href="<%= root_path %>" class="Nav__logo">
        </a>
        <div class="Nav__pullout">
          <ul class="Nav__links" style="left: 55%;">
            <li class="Nav__item">
              <%= link_to 'Why Apply', about_path, class: 'Nav__link' %>
            </li>
            <li class="Nav__item">
            </li>
            <li class="Nav__item">
              <%= link_to 'Upcoming Events', events_path, class: 'Nav__link' %>
            </li>
          </ul>
          <ul class="Nav__app-links">
            <li class="Nav__item">
              <i class="fa fa-phone" style="
              padding-right: 9px;
              padding-top: 3px;
              "></i>
              <a class=" Nav__log nav-number" href="tel:917-818-2633">917-818-2633</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>

app/views/layouts/_footer.html.erb
<footer class="Footer Section Section--even">
  <p style="margin: 0 auto; text-align: center"> Questions? Get in touch.</p>
  <p style="margin: 0 auto; text-align: center">  <a href="https://calendly.com/jigsaw-labs/information-chat?month=2019-11" >Let's chat!</a></p>
  <!-- Calendly inline widget begin -->
  <div class="Footer__container">
    <a href="/" class="Footer__logo">
    </a>
    <div class="Footer__links-container">
      <div class="Footer__links">
        <div class="Footer__links-main">
          <%= link_to 'Apply', new_application_path, class: 'gtag_target Footer__link' %>
          <%= link_to 'Course Details', course_details_path, class: 'Footer__link' %>
        </div>
        <div class="Footer__links-secondary">
          <%= link_to 'Free Course', course_signup_path, class: 'Footer__link' %>
          <%= link_to 'Upcoming Events', events_path, class: 'Footer__link' %>
        </div>
      </div>
    </div>
    <ul class="Footer__legal-list">
      <li class="Footer__legal-item">
        © 2022 Jigsaw Labs
      </li>
      <li class="Footer__legal-item">
        <a class="Footer__legal-link" href="/tos">Terms of Service</a>
      </li>
    </ul>
  </div>
</footer>
</div>
</body>
</html>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <style>
@font-face {
  src: url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.eot");
  src: url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.eot?#iefix") format("embedded-opentype"), url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.woff2") format("woff2"), url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.woff") format("woff"), url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.svg#Typotheque_webfonts_service") format("svg");
}

 <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Actor" />
    </style>
  </head>
  <body class=" ">
  <div class="container">
  <nav class="navbar navbar-expand fixed-top Nav__wrapper--opaque">
  <%= link_to root_path, class: 'navbar-brand Nav__logo' do %>
      <%= image_tag('general/jigsaw-text.svg', class: "svg-color") %>
    <% end %>

  <div class="navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="Nav__item d-none d-md-block">
        <%= link_to 'Free Curriculum', "/free", class: 'Nav__link ' %>
      </li>
      <li class="Nav__item d-none d-md-block">
        <%= link_to 'Why Data Engineering', "/course_details", class: 'Nav__link Nav__log' %>
      </li>
      <li class="Nav__item d-none d-sm-none d-md-none d-lg-block">
        <%= link_to 'Free Workshops', events_path, class: 'Nav__link' %>
      </li>
      <li class="Nav__item d-none d-sm-none d-md-none d-lg-block">
        <%= link_to 'Blog', "/blog", class: 'Nav__link ' %>
      </li>
    </ul>
      <%= link_to 'Apply Now', new_application_path, class: 'gtag_target js--signup-modal-trigger Button Button__purple Effect Effect-1' %>
    
  </div>
</nav>


  

app/views/layouts/_navbar_gray.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <style>
@font-face {
  src: url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.eot");
  src: url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.eot?#iefix") format("embedded-opentype"), url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.woff2") format("woff2"), url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.woff") format("woff"), url("https://s3-us-west-1.amazonaws.com/fonts-california.typotheque.com/WF-029669-009918-001560-fa6dd062b0c32d6d9a297bd175bb0381.svg#Typotheque_webfonts_service") format("svg");
}

 <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Actor" />
    </style>
  </head>
  <body class=" ">
    <div class="Nav__wrapper   Nav__wrapper--opaque " style="background: #f1f2f7 ">
      <nav class="Nav">
        <%= link_to root_path, class: 'Nav__logo' do %>
          <%= image_tag('general/jigsaw-text.svg', class: "svg-color") %>
        <% end %>
        </a>
        <div class="Nav__pullout">
          <ul class="Nav__links" style="left: 55%;">
            <li class="Nav__item">
              <%= link_to 'Free Curriculum', "/free", class: 'Nav__link Nav__log' %>
            </li>
            <li class="Nav__item">
              <%= link_to 'Course Details', "/course_details", class: 'Nav__link Nav__log' %>
            </li>
            <li class="Nav__item">
              <%= link_to 'Upcoming Workshops', events_path, class: 'Nav__link' %>
            </li>
            <li class="Nav__item">
              <%= link_to 'Blog', "/blog", class: 'Nav__link Nav__log' %>
            </li>
          </ul>
          <ul class="Nav__app-links">
            <li class="Nav__item">

            </li>
            <li class="Nav__item Nav__trial-wrapper">
              <%= link_to 'Apply Now', new_application_path, class: 'gtag_target js--signup-modal-trigger Button Button__purple Effect Effect-1' %>
            </li>
          </ul>
        </div>
      </nav>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="fas fa-puzzle-piece"> Jigsaw Labs - Data Engineering Course part-time and live online. </title>

    <meta name="theme-color" content="#caccf1" />
    <meta charset="utf-8" />
    <meta property="og:url" content="https://www.jigsawlabs.io/" />
    <meta property="og:title" content="Data Engineering Course Part-Time and Live Online" />
    <meta property="og:description" content="A part-time coding bootcamp teaching data engineering courses online." />
    <meta property="og:image" content="https://www.jigsawlabs.io/assets/general/jigsaw-touched-1195d5a8233ed2034df75c15d9188230f4f5f1f2ecf094ea0fb641a66f34e258.svg" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, width=device-width">
    <meta name="author" content="Jigsaw Labs" />
    <meta name="description" content="Learn data engineering, Python, SQL and Cloud Computing in our part time class." />
    <meta name="keywords" content="data engineering, docker, kubernetes, Spark, Pyspark, DBT, airflow, AWS, data science, machine learning, python, statistics, coding, bootcamp, course, programming, big data, deep learning" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="application-name" content="Jigsaw Labs" />
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta http-equiv="X-UA-Compatible" content="IE=11">
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156462054-1"></script>

    <%= javascript_pack_tag "application" %>

    <script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var key=analytics.methods[e];analytics[key]=analytics.factory(key)}analytics.load=function(key,e){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src="https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);analytics._loadOptions=e};analytics._writeKey="DZguFrXEzMM9uXNynl58K1kixJQvnuNK";;analytics.SNIPPET_VERSION="4.15.3";
  analytics.load("DZguFrXEzMM9uXNynl58K1kixJQvnuNK");
  analytics.page();
  }}();
  </script>

    <!-- Start of Mixpanel embed code -->
    <script type="text/javascript">
    (function(f,b){if(!b.__SV){var e,g,i,h;window.mixpanel=b;b._i=[];b.init=function(e,f,c){function g(a,d){var b=d.split(".");2==b.length&&(a=a[b[0]],d=b[1]);a[d]=function(){a.push([d].concat(Array.prototype.slice.call(arguments,0)))}}var a=b;"undefined"!==typeof c?a=b[c]=[]:c="mixpanel";a.people=a.people||[];a.toString=function(a){var d="mixpanel";"mixpanel"!==c&&(d+="."+c);a||(d+=" (stub)");return d};a.people.toString=function(){return a.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking start_batch_senders people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
    for(h=0;h<i.length;h++)g(a,i[h]);var j="set set_once union unset remove delete".split(" ");a.get_group=function(){function b(c){d[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));a.push([e,call2])}}for(var d={},e=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<j.length;c++)b(j[c]);return d};b._i.push([e,f,c])};b.__SV=1.2;e=f.createElement("script");e.type="text/javascript";e.async=!0;e.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
    MIXPANEL_CUSTOM_LIB_URL:"file:"===f.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";g=f.getElementsByTagName("script")[0];g.parentNode.insertBefore(e,g)}})(document,window.mixpanel||[]);



    var productionHost = 'www.jigsawlabs.io';
    var devToken = '6c636bd5b388918129366b40d7a2a816';
    var prodToken = '5d65277cdcc92c9432e0e5fccda219ee';

    /* If the hostname is anything other than your production domain, initialize the Mixpanel library with your Development Token */

    if (window.location.hostname.toLowerCase().search(productionHost) < 0) {
        mixpanel.init(devToken);
    } else {
        mixpanel.init(prodToken);
    }

    document.addEventListener('turbolinks:load', function() {
      let signupButton = document.querySelector('.js--signup-modal-trigger')
      signupButton.addEventListener('click', function(){
        console.log('clicked apply')
        mixpanel.track('Clicked Apply')
        
      })
    })
    </script>
    <!-- End of Mixpanel Embed Code -->

<!-- Start of Google Analytics & AdWords Embed Code -->

    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-156462054-1');
      gtag('config', 'AW-300783493');
    </script>
    <!-- Event snippet for Book appointment conversion page
In your html page, add the snippet and call gtag_report_conversion when someone clicks on the chosen link or button. -->
<script>
function gtag_report_conversion(url) {
  var callback = function () {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  };
  gtag('event', 'conversion', {
      'send_to': 'AW-300783493/ZvzGCLbi7PQCEIWvto8B',
      'event_callback': callback
  });
  return false;
}
</script>
<!-- End of Google Analytics & AdWords Embed Code -->



    <script>(function(c,a){if(!a.__SV){var b=window;try{var d,m,j,k=b.location,f=k.hash;d=function(a,b){return(m=a.match(RegExp(b+"=([^&]*)")))?m[1]:null};f&&d(f,"state")&&(j=JSON.parse(decodeURIComponent(d(f,"state"))),"mpeditor"===j.action&&(b.sessionStorage.setItem("_mpcehash",f),history.replaceState(j.desiredHash||"",c.title,k.pathname+k.search)))}catch(n){}var l,h;window.mixpanel=a;a._i=[];a.init=function(b,d,g){function c(b,i){var a=i.split(".");2==a.length&&(b=b[a[0]],i=a[1]);b[i]=function(){b.push([i].concat(Array.prototype.slice.call(arguments,
0)))}}var e=a;"undefined"!==typeof g?e=a[g]=[]:g="mixpanel";e.people=e.people||[];e.toString=function(b){var a="mixpanel";"mixpanel"!==g&&(a+="."+g);b||(a+=" (stub)");return a};e.people.toString=function(){return e.toString(1)+".people (stub)"};l="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking start_batch_senders people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
for(h=0;h<l.length;h++)c(e,l[h]);var f="set set_once union unset remove delete".split(" ");e.get_group=function(){function a(c){b[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));e.push([d,call2])}}for(var b={},d=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<f.length;c++)a(f[c]);return b};a._i.push([b,d,g])};a.__SV=1.2;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
MIXPANEL_CUSTOM_LIB_URL:"file:"===c.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)}})(document,window.mixpanel||[]);

var productionHost = 'www.jigsawlabs.io';
var initToken = '';

if (window.location.hostname.toLowerCase().search(productionHost) < 0) {
  initToken = '6c636bd5b388918129366b40d7a2a816';
} else {
  initToken = '5d65277cdcc92c9432e0e5fccda219ee';
}

mixpanel.init(initToken, {batch_requests: true})</script>


    <%= favicon_link_tag asset_path('general/jigsaw-cropped-transparent.png'), :rel => 'icon', :type => "image/x-icon" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="google-site-verification" content="jDhwo9AhWJnDJtb9VLSYiHqZaixZEm22qsy28eUnfZk" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script', 'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '2399815900240753');
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=2399815900240753&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->

<!-- Begin Fullstory Link -->
<script>
window['_fs_debug'] = false;
window['_fs_host'] = 'fullstory.com';
window['_fs_script'] = 'edge.fullstory.com/s/fs.js';
window['_fs_org'] = '18QCYK';
window['_fs_namespace'] = 'FS';
(function(m,n,e,t,l,o,g,y){
    if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
    g=m[e]=function(a,b,s){g.q?g.q.push([a,b,s]):g._api(a,b,s);};g.q=[];
    o=n.createElement(t);o.async=1;o.crossOrigin='anonymous';o.src='https://'+_fs_script;
    y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
    g.identify=function(i,v,s){g(l,{uid:i},s);if(v)g(l,v,s)};g.setUserVars=function(v,s){g(l,v,s)};g.event=function(i,v,s){g('event',{n:i,p:v},s)};
    g.anonymize=function(){g.identify(!!0)};
    g.shutdown=function(){g("rec",!1)};g.restart=function(){g("rec",!0)};
    g.log = function(a,b){g("log",[a,b])};
    g.consent=function(a){g("consent",!arguments.length||a)};
    g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
    g.clearUserCookie=function(){};
    g.setVars=function(n, p){g('setVars',[n,p]);};
    g._w={};y='XMLHttpRequest';g._w[y]=m[y];y='fetch';g._w[y]=m[y];
    if(m[y])m[y]=function(){return g._w[y].apply(this,arguments)};
    g._v="1.3.0";
})(window,document,window['_fs_namespace'],'script','user');
</script>
<!-- End Fullstory Link -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/nav_more.html.erb
<div class="container" style="margin: 0px;">
    
      <nav class="Nav__wrapper--opaque navbar-fixed-top navbar navbar-expand-lg" style="position: fixed">
      
        <%= link_to root_path, class: 'Nav__logo col-1' do %>
          <%= image_tag('general/jigsaw-text.svg', class: "svg-color") %>
        <% end %>
        </a>
        <div class="col-11">
          <ul class="Nav__links" style="">
            <li class="Nav__item">
              <%= link_to 'Free Curriculum', "/free", class: 'Nav__link Nav__log' %>
            </li>
          </ul>
        </div>
      </nav>
    
  </div>

app/views/layouts/navbar_notes.html.erb
<nav class="Nav__wrapper--opaque navbar-fixed-top" style="position: fixed">
      <%= link_to root_path, class: 'Nav__logo' do %>
        <%= image_tag('general/jigsaw-text.svg', class: "svg-color") %>
      <% end %>
      </a>
      <div class="">
        <ul class="Nav__links" style="">
          <li class="Nav__item">
            <%= link_to 'Free Curriculum', "/free", class: 'Nav__link Nav__log' %>
          </li>
          <li class="Nav__item">
            <%= link_to 'Why Data Engineering', "/course_details", class: 'Nav__link Nav__log' %>
          </li>
          <li class="Nav__item">
            <%= link_to 'Upcoming Workshops', events_path, class: 'Nav__link' %>
          </li>
          <li class="Nav__item">
            <%= link_to 'Blog', "/blog", class: 'Nav__link Nav__log' %>
          </li>
        </ul>
        <ul class="Nav__app-links">
          <li class="Nav__item Nav__trial-wrapper">
            <%= link_to 'Apply Now', new_application_path, class: 'gtag_target js--signup-modal-trigger Button Button__purple Effect Effect-1' %>
          </li>
        </ul>
      </div>
      
    </nav>